index:
    path: /
    controller: App\Controller\IndexController::index

login:
    path: /login
    controller: App\Controller\IndexController::login
app_logout:
    path: /logout
    methods: GET
nouveau:
    path: /nouveau
    controller: App\Controller\ElementController::addElement
edit_element:
    path: /element/edit/{id}
    controller: App\Controller\ElementController::editElement
    requirements:
        id: '\d+'
show_element:
    path: /element/{id}
    controller: App\Controller\ElementController::showElement
    requirements:
        id: '\d+'
switch_publish_element:
    path: /element/unpublish/{id}
    controller: App\Controller\ElementController::switchPublishElement
    requirements:
        id: '\d+'
delete_element:
    path: /element/delete/{id}
    controller: App\Controller\ElementController::deleteElement
    requirements:
        id: '\d+'
list_element:
    path: /elements
    controller: App\Controller\ElementController::listElements
#ABOUT
about:
    path: /a-propos
    controller: App\Controller\IndexController::about

#CREATIONS
creations:
    path: /creations
    controller: App\Controller\IndexController::creations

#BLOG
blog:
    path: /blog
    controller: App\Controller\IndexController::blog
new_article:
    path: /admin/nouvel-article
    controller: App\Controller\ArticleController::addArticle
edit_article:
    path: /article/edit/{id}
    controller: App\Controller\ArticleController::editArticle
    requirements:
        id: '\d+'
show_article:
    path: /article/{id}
    controller: App\Controller\ArticleController::showArticle
    requirements:
        id: '\d+'
switch_publish_article:
    path: /article/unpublish/{id}
    controller: App\Controller\ArticleController::switchPublishArticle
    requirements:
        id: '\d+'
delete_article:
    path: /article/delete/{id}
    controller: App\Controller\ArticleController::deleteArticle
    requirements:
        id: '\d+'
list_articles:
    path: /articles
    controller: App\Controller\ArticleController::listArticles

contact:
    path: /contact
    controller: App\Controller\IndexController::contact

#testform:
#    path: /testform
#    controller: App\Controller\ElementController::new